# Generated by Django 4.0.4 on 2022-04-30 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='mbtiModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeName', models.TextField(default='')),
                ('typeNickname', models.TextField(default='')),
                ('workStyleSummary', models.TextField(default='')),
                ('communication', models.TextField(default='')),
                ('meeting', models.TextField(default='')),
                ('emailing', models.TextField(default='')),
                ('feedback', models.TextField(default='')),
                ('conflict', models.TextField(default='')),
                ('conclusion', models.TextField(default='')),
                ('headerImgUrl', models.TextField(default='')),
                ('overview', models.TextField(default='')),
                ('strengths', models.TextField(default='')),
                ('weaknesses', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='MBTITest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.TextField()),
                ('input', models.TextField()),
                ('date', models.DateTimeField()),
                ('type', models.TextField(max_length=4)),
                ('IvsE', models.TextField(default='', max_length=1)),
                ('IvsS', models.TextField(default='', max_length=1)),
                ('TvsF', models.TextField(default='', max_length=1)),
                ('JvsP', models.TextField(default='', max_length=1)),
                ('probability', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('profile_picture_url', models.TextField(default='/static/assets/img/profileHolder.png')),
                ('initiator',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.TextField(default='Software Engineer')),
                ('team', models.TextField(default='App Development')),
                ('testResult',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.mbtitest')),
                (
                'user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
