# Generated by Django 3.2.6 on 2022-04-14 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
