# Generated by Django 3.2.6 on 2022-04-14 19:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('home', '0008_siteuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteUser',
        ),
    ]
