# Generated by Django 3.2.6 on 2022-04-19 23:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0010_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='MBTITests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.TextField()),
                ('input', models.TextField()),
                ('date', models.DateTimeField()),
                ('result', models.TextField(max_length=4)),
                ('initiator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
