# Generated by Django 3.2.6 on 2022-04-20 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_mbtitests_initiator'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mbti_nickname',
            field=models.TextField(default='You are currently untyped.'),
        ),
    ]
