# Generated by Django 3.2.6 on 2022-04-20 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_profile_mbti_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mbti_nickname',
            field=models.TextField(),
        ),
    ]
