# Generated by Django 4.0.4 on 2022-04-21 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_mbtitest_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mbtitest',
            name='profile_picture',
        ),
    ]
