# Generated by Django 4.0.4 on 2022-04-21 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_remove_mbtitest_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='mbtitest',
            name='profile_picture',
            field=models.ImageField(blank=True, default='/Users/andricozacharia/Desktop/FYP/apps/static', max_length=100000, upload_to='profile_pictures/'),
        ),
    ]
