# Generated by Django 4.0.4 on 2022-04-23 23:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('home', '0018_mbtitest_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='mbtitest',
            name='probability',
            field=models.DecimalField(decimal_places=16, default=0.0, max_digits=18),
        ),
    ]
