# Generated by Django 4.0.4 on 2022-04-24 13:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('home', '0020_rename_result_mbtitest_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mbtitest',
            name='probability',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
    ]
