# Generated by Django 4.0.4 on 2022-04-24 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_mbtitest_probability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mbtitest',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='mbtitest',
            name='profile_picture_url',
            field=models.TextField(default='/static/assets/img/team-2.jpg'),
        ),
    ]
