# Generated by Django 4.0.4 on 2022-04-25 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_remove_mbtitest_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mbtitest',
            name='FvsT',
            field=models.TextField(default='', max_length=1),
        ),
        migrations.AddField(
            model_name='mbtitest',
            name='IvsE',
            field=models.TextField(default='', max_length=1),
        ),
        migrations.AddField(
            model_name='mbtitest',
            name='IvsS',
            field=models.TextField(default='', max_length=1),
        ),
        migrations.AddField(
            model_name='mbtitest',
            name='JvsP',
            field=models.TextField(default='', max_length=1),
        ),
    ]
