# Generated by Django 4.0.4 on 2022-04-25 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_remove_profile_mbti_nickname_mbtitest_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mbtitest',
            name='nickname',
        ),
    ]
