# Generated by Django 4.0.4 on 2022-04-25 00:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('home', '0025_remove_mbtitest_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mbti_nickname',
            field=models.TextField(default='lll'),
            preserve_default=False,
        ),
    ]
