# Generated by Django 4.0.4 on 2022-04-25 00:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('home', '0026_profile_mbti_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='mbti_nickname',
        ),
    ]
