# Generated by Django 4.0.4 on 2022-04-25 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_remove_profile_mbti_nickname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mbtitest',
            old_name='FvsT',
            new_name='TvsF',
        ),
    ]
