# Generated by Django 4.0.4 on 2022-04-25 16:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('home', '0028_rename_fvst_mbtitest_tvsf'),
    ]

    operations = [
        migrations.CreateModel(
            name='mbtiModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeName', models.TextField(default='', max_length=1)),
                ('typeNickname', models.TextField(default='', max_length=1)),
                ('workStyleSummary', models.TextField(default='', max_length=1)),
                ('communication', models.TextField(default='', max_length=1)),
                ('meeting', models.TextField(default='', max_length=1)),
                ('emailing', models.TextField(default='', max_length=1)),
                ('feedback', models.TextField(default='', max_length=1)),
                ('conflict', models.TextField(default='', max_length=1)),
                ('conclusion', models.TextField(default='', max_length=1)),
            ],
        ),
    ]
