# Generated by Django 4.0.4 on 2022-04-25 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_mbtimodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mbtimodel',
            name='communication',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='mbtimodel',
            name='conclusion',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='mbtimodel',
            name='conflict',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='mbtimodel',
            name='emailing',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='mbtimodel',
            name='feedback',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='mbtimodel',
            name='meeting',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='mbtimodel',
            name='typeName',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='mbtimodel',
            name='typeNickname',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='mbtimodel',
            name='workStyleSummary',
            field=models.TextField(default=''),
        ),
    ]
