# Generated by Django 4.0.4 on 2022-04-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('home', '0030_alter_mbtimodel_communication_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mbtimodel',
            name='headerImgUrl',
            field=models.TextField(default=''),
        ),
    ]
