# Generated by Django 4.0.4 on 2022-04-25 18:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('home', '0032_mbtimodel_overview'),
    ]

    operations = [
        migrations.AddField(
            model_name='mbtimodel',
            name='strengths',
            field=models.TextField(default=''),
        ),
    ]
