# Generated by Django 4.0.4 on 2022-04-25 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_mbtimodel_strengths'),
    ]

    operations = [
        migrations.AddField(
            model_name='mbtimodel',
            name='weaknesses',
            field=models.TextField(default=''),
        ),
    ]
