# Generated by Django 4.0.4 on 2022-04-25 18:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_mbtimodel_weaknesses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mbtimodel',
            name='communication',
            field=ckeditor.fields.RichTextField(default=''),
        ),
        migrations.AlterField(
            model_name='mbtimodel',
            name='conclusion',
            field=ckeditor.fields.RichTextField(default=''),
        ),
        migrations.AlterField(
            model_name='mbtimodel',
            name='conflict',
            field=ckeditor.fields.RichTextField(default=''),
        ),
        migrations.AlterField(
            model_name='mbtimodel',
            name='emailing',
            field=ckeditor.fields.RichTextField(default=''),
        ),
        migrations.AlterField(
            model_name='mbtimodel',
            name='feedback',
            field=ckeditor.fields.RichTextField(default=''),
        ),
        migrations.AlterField(
            model_name='mbtimodel',
            name='headerImgUrl',
            field=ckeditor.fields.RichTextField(default=''),
        ),
        migrations.AlterField(
            model_name='mbtimodel',
            name='meeting',
            field=ckeditor.fields.RichTextField(default=''),
        ),
        migrations.AlterField(
            model_name='mbtimodel',
            name='overview',
            field=ckeditor.fields.RichTextField(default=''),
        ),
        migrations.AlterField(
            model_name='mbtimodel',
            name='strengths',
            field=ckeditor.fields.RichTextField(default=''),
        ),
        migrations.AlterField(
            model_name='mbtimodel',
            name='weaknesses',
            field=ckeditor.fields.RichTextField(default=''),
        ),
        migrations.AlterField(
            model_name='mbtimodel',
            name='workStyleSummary',
            field=ckeditor.fields.RichTextField(default=''),
        ),
    ]
