# Generated by Django 4.0.4 on 2022-04-25 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_alter_mbtimodel_communication_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mbtimodel',
            name='communication',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='mbtimodel',
            name='conclusion',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='mbtimodel',
            name='conflict',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='mbtimodel',
            name='emailing',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='mbtimodel',
            name='feedback',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='mbtimodel',
            name='headerImgUrl',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='mbtimodel',
            name='meeting',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='mbtimodel',
            name='overview',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='mbtimodel',
            name='strengths',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='mbtimodel',
            name='weaknesses',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='mbtimodel',
            name='workStyleSummary',
            field=models.TextField(default=''),
        ),
    ]
