# Generated by Django 4.0.4 on 2022-04-27 00:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('home', '0036_alter_mbtimodel_communication_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.TextField(default='Employee'),
        ),
    ]
