# Generated by Django 4.0.4 on 2022-04-27 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mbti_type',
            field=models.TextField(default='Untyped', max_length=4),
        ),
    ]
