# Generated by Django 4.0.4 on 2022-04-27 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_remove_profile_mbti_result_profile_mbtitest_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='MBTITest_id',
        ),
        migrations.AddField(
            model_name='profile',
            name='testResult',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='home.mbtitest'),
        ),
    ]
